#+TITLE: pyCVRPLIB
This Python package provides functions to read and download instances from the Capacitated Vehicle Routing Problem Library ([[http://vrp.atd-lab.inf.puc-rio.br/index.php/en/][CVRPLIB]]), which contains a large collection of CVRP instances and also keeps track of the currently best known solutions.

This package is inspired by [[https://github.com/chkwon/CVRPLIB.jl][CVRPLIB.jl]].

* Installation
This library works with Python 3.7+ and be installed using
#+begin_src python
pip install pycvrplib
#+end_src

* Usage
** Functions
Using this package is simple. We expose three functions =read=, =download= and =list_instances=. Reading works with the =.vrp= and =.sol= files that can be found on the CVRPLIB website. To directly download an instance and the corresponding solution, you must provide the instance name prefixed with the corresponding set name and a forward slash. For example, the =A-n32-k5= instance belongs to the set =A=, hence =A/A-n32-k5= is the correct name to download this instance.

#+begin_src python
import pycvrplib

# Read instances
instance = pycvrplib.read('/path/to/A-n32-k5.vrp')
instance, solution = pycvrplib.read(instance_path='/path/to/A-n32-k5.sol',
                                    solution_path='/path/to/A-n32-k5.sol')

# List all instance names including set name
pycvrplib.list_instances()

# Download instances: passed-in argument must be the full set and instance name
# Note that downloading may take a few seconds.
instance = pycvrplib.download('A/A-n32-k5')
instance, solution = pycvrplib.download('A/A-n32-k5', solution=True)
#+end_src

** Instance and Solution class
The =instance= and =solution= objects are defined by their respective classes as follows:
#+begin_src python
@dataclass
class Instance:
    name: str
    comment: str
    dimension: int
    capacity: int
    distances: List[List[float]]
    demands: List[int]
    depot: int
    coordinates: Optional[List[List[float]]] = None

@dataclass
class Solution:
    routes: List[int]
    cost: float
#+end_src


* Conventions
- The depot has index =0=, whereas customers are indexed from =1= to =n=.
- The distances are all assumed to be integral, where instances calculated by taking the Euclidean distance are rounded to the nearest integer. Note that some of the reported best known solutions have non-rounded distances and are thus floating point numbers. This is the case for the following data sets: =CMT=, =Rochat and Taillard=, =Golden=, =Li=, =Solomon=, =Homberger and Gehring=.

* Remarks
- Downloading and listing instances may take a while (a few seconds). Please let me know if you know how to fix this.
- The =XML100= data set, which contains 10000 CVRP instances for training ML algorithms, is not listed in =list_instances= and cannot be downloaded using the =download= function. Please download these instances directly from [[http://vrp.atd-lab.inf.puc-rio.br/index.php/en/][CVRPLIB]]. This package does support reading the instances.
- Our package currently does not support reading and downloading VRPTW instances, i.e., instances that belong to the =Solomon= and =Homberger and Gehring= set. Support for this will be in a later version.

