name: Publish

on:
  release:
    types: [ created ]

jobs:
  run:
    name: "Build and publish release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"

      - run: uv python install 3.12
      - run: uv build
      - run: uv publish
        env:
            UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
